        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
          include-prerelease: true

      - run: dotnet publish BBDown -r win-x64 -c Release -o artifact-x64
      - run: dotnet publish BBDown -r win-arm64 -c Release -o artifact-arm64
@@ -51,7 +50,6 @@ jobs:
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
          include-prerelease: true
      - run: apt-get install -y libicu-dev libcurl4-openssl-dev zlib1g-dev libkrb5-dev
      - run: dotnet publish BBDown -r linux-x64 -c Release -o artifact

@@ -73,7 +71,6 @@ jobs:
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
          include-prerelease: true
      - run: dotnet publish BBDown -r linux-arm64 -c Release -p:StripSymbols=true -p:CppCompilerAndLinker=clang-9 -p:SysRoot=/crossrootfs/arm64 -o artifact

      - name: Upload Artifact[linux-arm64]
@@ -94,7 +91,6 @@ jobs:
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
          include-prerelease: true
      - run: dotnet publish BBDown -r osx-arm64 -c Release -o artifact-arm64
      - run: dotnet publish BBDown -r osx-x64 -c Release -o artifact-x64
